apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
spec:
  goTemplate: true
  # goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: test-cluster
        url: https://kubernetes.default.svc

  template:
    metadata:
      name: '{{ .cluster }}-application'
    spec:
      project: default
      source:
        helm:
          valueFiles:
            - $values/helm-argo-repo/webapp/values.yaml

        repoURL: https://github.com/sanjaysam001/helm-argo-repo.git
        targetRevision: HEAD
        path: helm-argo-repo/webapp
      destination:
        server: '{{ .url }}'
        namespace: default

